name: Binaries

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        ghc: ["8.10.7"]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: haskell/actions/setup@v1
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 3.6.2.0

      - name: Configure project
        run: cabal configure --enable-tests --enable-benchmarks

      - name: Restore cabal cache
        uses: haskell-works/cabal-cache-action@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BINARY_CACHE_REGION: ${{ secrets.BINARY_CACHE_REGION }}
          BINARY_CACHE_URI: ${{ secrets.BINARY_CACHE_URI }}
        with:
          args: |
            sync-from-archive \
              --threads       "16" \
              --archive-uri   "$BINARY_CACHE_URI" \
              --region        "$BINARY_CACHE_REGION" \
              --store-path    "${{ steps.setup-haskell.outputs.cabal-store }}"

      - name: Build
        # Try building it twice in case of flakey builds on Windows
        run: |
          cabal build all --enable-tests --enable-benchmarks

      - name: Test
        run: |
          cabal test all --enable-tests --enable-benchmarks

      - name: Save cabal cache
        uses: haskell-works/cabal-cache-action@v1
        if: ${{ always() }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BINARY_CACHE_REGION: ${{ secrets.BINARY_CACHE_REGION }}
          BINARY_CACHE_URI: ${{ secrets.BINARY_CACHE_URI }}
        with:
          args: |
            sync-to-archive \
              --threads       "16" \
              --archive-uri   "$BINARY_CACHE_URI" \
              --region        "$BINARY_CACHE_REGION" \
              --store-path    "${{ steps.setup-haskell.outputs.cabal-store }}"

  check:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}

    steps:
      - uses: actions/checkout@v2

      - name: Check if cabal project is sane
        run: |
          PROJECT_DIR=$PWD
          mkdir -p $PROJECT_DIR/build/sdist
          for i in $(git ls-files | grep '\.cabal'); do
            cd $PROJECT_DIR && cd `dirname $i`
            cabal check
          done

      - name: Tag new version
        id: tag
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          server: http://hackage.haskell.org
          username: ${{ secrets.HACKAGE_USER }}
          password: ${{ secrets.HACKAGE_PASS }}
        run: |
          package_version="$(cat *.cabal | grep '^version:' | cut -d : -f 2 | xargs)"

          echo "Package version is v$package_version"

          git fetch --unshallow origin

          if git tag "v$package_version"; then
            echo "Tagging with new version "v$package_version""

            if git push origin "v$package_version"; then
              echo "Tagged with new version "v$package_version""

              echo "::set-output name=tag::v$package_version"
            fi
          fi
